### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by FinestArcadeArt** [marsohod4you/MBFTDI-SVF-Player#4]
**Making your GitHub project public is not the same as licensing your project**. Public projects are covered by [GitHub’s Terms of Service](https://help.github.com/en/github/site-policy/github-terms-of-service#3-ownership-of-content-right-to-post-and-license-grants), which allows others to view and fork your project, but **_your work otherwise comes with no permissions_**.

If you want others to use, distribute, modify, or contribute back to your project, you need to include an open source license. For example, someone cannot legally use any part of your GitHub project in their code, even if it’s public, unless you explicitly give them the right to do so.

**Comment by marsohod4you** [comment]
Fixed
